# ----
# Site

title: sprove for developers
description: 'sprove: API documentation'
url: https://developer.sprove.me
# google_analytics_key:
permalink: pretty
# baseurl: https://developer.sprove.me

# -----
# Build

timezone: Etc/GMT+1

collections:
  documentation:
    title: Documentation
    position_number: 1
  api_title_only:
    title: APIs
    position_number: 2
  property_api:
    title: Properties
    position_number: 3
  check_api:
    title: Checks
    position_number: 4

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "property_api"
    values:
      _hide_content: true
  -
    scope:
      type: "check_api"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
